version: "3"
services:
 reverseproxy:
  image: programmingwebsite/todo-reverseproxy
  ports:
   - 8888:8888
  restart: always
  depends_on:
   - backend-todo
   - frontend     
 backend-todo:
  image: programmingwebsite/restapi-todo
  volumes: 
   - $HOME/.aws:/root/.aws   
  environment:
   USERS_TODO_TABLE: $USERS_TODO_TABLE 
   USERID_INDEX: $USERID_INDEX 
   TODOS_S3_BUCKET: $TODOS_S3_BUCKET 
   THUMBNAILS_S3_BUCKET: $THUMBNAILS_S3_BUCKET 
   SIGNED_URL_EXPIRATION: $SIGNED_URL_EXPIRATION 
   AWS_REGION: $AWS_REGION
   AWS_PROFILE: $AWS_PROFILE
   TODO_VERSION: "v2" 
   URL: $URL    
 frontend:
   image: programmingwebsite/todo-frontend:v2
   ports:
    - 3000:3000
