apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-todo
  name: backend-todo
spec:
 ports:
 - name: "8888"
   port: 8888  
   targetPort: 8888   
 selector:
  service: backend-todo
