apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend
  name: frontend
  annotations:
    external-dns.alpha.kubernetes.io/hostname: programming.website.
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:765350246637:certificate/49813b86-d6d7-4c98-8259-d271326810fe
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"  
spec:
  type: LoadBalancer  
  ports:
   - name: "3000"
     port: 3000
     targetPort: 3000
  selector:
    service: frontend
