 
apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy 
spec:
  ports:
   - name: "8888"
     port: 8888
     targetPort: 8888
  selector:
    service: reverseproxy
  type: LoadBalancer  